#!/bin/sh 
# make the pdf documentation and put them to a subdirectory ElmerDocumentation

modules="latex-elmergui latex-tutorials-CL latex-tutorials-GUI latex-elmer-getstart latex-tex-start latex-tex-template"
for m in $modules; do
  cd $m && make manual && make install && make clean && cd ..
done

mkdir -p ElmerManuals
/bin/mv -f *.pdf ElmerManuals
