#!/bin/sh 
# make the pdf documentation and put them to a subdirectory ElmerDocumentation

modules="gui tutorials-GUI tutorials-CL"
for m in $modules; do
  cd $m && make manual && make install && make clean && cd ..
done

mkdir -p ElmerManuals
/bin/mv -f *.pdf ElmerManuals
